# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec634105decc808c671d1495bdc61e38db3fc0dc8ae4b368bd5285c0f0833f71c0323b842110a9fda929143fab6e3311d6e3162a7f070b4bcd86b666964cb02b

test:
  secret_key_base: 90f85264bd1964cf68c898fdce94770d4d222ea94ffb50615572a7c892e9f2871d8cf4b324aa6d348f9be3fd68c5d5760b55ce373482b448205f013b90c92185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
